### ISSUE TITLE
Pass through POSIX objects in lubridate::ymd_hms() and friends

### ISSUE THREAD

**Issue by leungi** [tidyverse/lubridate#799] opened 2019-10-06 21:50 UTC
`lubridate::ymd_hms()` fail to parse even though it should; reprex below.

`anytime::anytime()` works.

```r
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:lubridate':
#> 
#>     intersect, setdiff, union
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(anytime)
#> Warning: package 'anytime' was built under R version 3.5.3

packageVersion("lubridate")
#> [1] '1.7.4'
packageVersion("dplyr")
#> [1] '0.8.3'
packageVersion("anytime")
#> [1] '0.3.3'

df <- structure(
  list(
    a = structure(
      c(
        1421368200,
        1421368200,
        1421368200,
        1421368200,
        1421368200,
        1421368200
      ),
      class = c(
        "POSIXct",
        "POSIXt"
      ),
      tzone = "UTC"
    ),
    b = structure(
      c(
        1437436800,
        1549497600,
        1516406400,
        1542153600,
        1495324800,
        1526860800
      ),
      class = c(
        "POSIXct",
        "POSIXt"
      ),
      tzone = "UTC"
    )
  ),
  row.names = c(NA, -6L),
  class = c(
    "tbl_df",
    "tbl",
    "data.frame"
  )
)

df %>% 
  mutate(flag = ymd_hms(a) > ymd_hms(b))
#> Warning: All formats failed to parse. No formats found.
#> # A tibble: 6 x 3
#>   a                   b                   flag 
#>   <dttm>              <dttm>              <lgl>
#> 1 2015-01-16 00:30:00 2015-07-21 00:00:00 NA   
#> 2 2015-01-16 00:30:00 2019-02-07 00:00:00 NA   
#> 3 2015-01-16 00:30:00 2018-01-20 00:00:00 NA   
#> 4 2015-01-16 00:30:00 2018-11-14 00:00:00 NA   
#> 5 2015-01-16 00:30:00 2017-05-21 00:00:00 NA   
#> 6 2015-01-16 00:30:00 2018-05-21 00:00:00 NA

df %>% 
  mutate(flag = anytime(a) > anytime(b))
#> # A tibble: 6 x 3
#>   a                   b                   flag 
#>   <dttm>              <dttm>              <lgl>
#> 1 2015-01-16 00:30:00 2015-07-21 00:00:00 FALSE
#> 2 2015-01-16 00:30:00 2019-02-07 00:00:00 FALSE
#> 3 2015-01-16 00:30:00 2018-01-20 00:00:00 FALSE
#> 4 2015-01-16 00:30:00 2018-11-14 00:00:00 FALSE
#> 5 2015-01-16 00:30:00 2017-05-21 00:00:00 FALSE
#> 6 2015-01-16 00:30:00 2018-05-21 00:00:00 FALSE
```

**Comment by vspinu** [comment] 2019-10-07 08:59
Your reprex is unnecessary convoluted. It could have been done just as

```R
> x <- ymd_hms("2015-07-21 00:00:00")
> ymd_hms(x)
[1] NA
Warning message:
All formats failed to parse. No formats found. 
```

The problem is that `ymd_hms` is a parser, and that means it accepts a character string and converts to a date.time. Internally, if object is not a character vecror it is converted to, so you end up parsing `as.character(x)` which is `"2015-07-21")` and cannot be parsed. 

Anyways, if you want anytime like converter, use `as_datetime`, or `as_date`. 

I will change the internals of ymd_hms and other parsers to handle posix objects differently as this is a common "problem". Same problem as in #797.

**Comment by leungi** [comment] 2019-10-07 12:59
Thanks for the explanation @vspinu.

I didn't realize the cause lies with `ymd_hms()` being unable to operate on other data types aside from character; I had thought that it may be to do with the data being in a tibble 😅, hence the long-winded reprex.

**Comment by hadley** [comment] 2019-11-19 23:41
Duplicate of #739

**Closed by hadley** 2019-11-19 23:41 UTC
Labels: feature
