### ISSUE TITLE
Error installing lubridate on Mac OS X 10.6.8

### ISSUE THREAD

**Issue by sylwiaoz** [tidyverse/lubridate#670] opened 2018-05-06 18:22 UTC
Hello,

I am using an old version of R (3.2.1) compatible with Snow Leopard 10.6.8.

I need to use the package "tidyverse". I could not install it with the command install.packages("tidyverse") because of a compilation error with lubridate (see the error log below). 

I tried to intall it from GitHub but the installation faills: "Installation failed: SSL connect error".

Any ideas what the problem is and how to solve it?

Cheers,
Sylwia

* installing *source* package ‘lubridate’ ...
** package ‘lubridate’ correctement décompressé et sommes MD5 vérifiées
** libs
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"      -c RcppExports.cpp -o RcppExports.o
llvm-gcc-4.2 -arch x86_64 -std=gnu99 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"   -fPIC  -mtune=core2 -g -O2  -c datetime.c -o datetime.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [RcppExports.o] Error 127 (ignored)
llvm-gcc-4.2 -arch x86_64 -std=gnu99 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"   -fPIC  -mtune=core2 -g -O2  -c period.c -o period.o
llvm-gcc-4.2 -arch x86_64 -std=gnu99 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"   -fPIC  -mtune=core2 -g -O2  -c tparse.c -o tparse.o
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"      -c update.cpp -o update.o
llvm-gcc-4.2 -arch x86_64 -std=gnu99 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"   -fPIC  -mtune=core2 -g -O2  -c utils.c -o utils.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [update.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"      -c cctz/src/time_zone_fixed.cc -o cctz/src/time_zone_fixed.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"      -c cctz/src/time_zone_if.cc -o cctz/src/time_zone_if.o
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"      -c cctz/src/time_zone_impl.cc -o cctz/src/time_zone_impl.o
make: [cctz/src/time_zone_fixed.o] Error 127 (ignored)
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [cctz/src/time_zone_if.o] Error 127 (ignored)
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [cctz/src/time_zone_impl.o] Error 127 (ignored)
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [cctz/src/time_zone_info.o] Error 127 (ignored)
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [cctz/src/time_zone_libc.o] Error 127 (ignored)
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [cctz/src/time_zone_lookup.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"      -c cctz/src/time_zone_info.cc -o cctz/src/time_zone_info.o
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"      -c cctz/src/time_zone_libc.cc -o cctz/src/time_zone_libc.o
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"      -c cctz/src/time_zone_lookup.cc -o cctz/src/time_zone_lookup.o
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"      -c cctz/src/time_zone_posix.cc -o cctz/src/time_zone_posix.o
ar rcs libcctz.a ./cctz/src/time_zone_fixed.o ./cctz/src/time_zone_if.o ./cctz/src/time_zone_impl.o ./cctz/src/time_zone_info.o ./cctz/src/time_zone_libc.o ./cctz/src/time_zone_lookup.o ./cctz/src/time_zone_posix.o 
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [cctz/src/time_zone_posix.o] Error 127 (ignored)
ar: ./cctz/src/time_zone_fixed.o: No such file or directory
ar: ./cctz/src/time_zone_if.o: No such file or directory
ar: ./cctz/src/time_zone_impl.o: No such file or directory
ar: ./cctz/src/time_zone_info.o: No such file or directory
ar: ./cctz/src/time_zone_libc.o: No such file or directory
ar: ./cctz/src/time_zone_lookup.o: No such file or directory
ar: ./cctz/src/time_zone_posix.o: No such file or directory
make: *** [libcctz.a] Error 1
ERROR: compilation failed for package ‘lubridate’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/lubridate’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/lubridate’

**Comment by vspinu** [comment] 2018-05-07 08:26
I think this is a duplicate of #666. Could you try to install version from github?

**Comment by vspinu** [comment] 2018-05-07 08:28
>  "Installation failed: SSL connect error".

It's a connection error, not specific to lubridate or devtools. Just retry a few minutes later. The command should be `devtools::install_github("tidyverse/lubridate")`.

**Comment by sylwiaoz** [comment] 2018-05-07 11:17
Hello, I tried the command several times so far since this morning but to no avail.

Would you be able to provide a link where I can download the package and install it from local()?

**Comment by vspinu** [comment] 2018-05-07 11:32
There is a button on the front page of the repo `clone or download` which you can use to either pull with git or download a zip archive.

**Comment by sylwiaoz** [comment] 2018-05-07 13:52
The issue is still there (the same I guess?):

> devtools::install_local("/Users/sylwia/Downloads/lubridate-master")
Installing lubridate
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/BM/BMXetWRWEZCEQYjc7kXp2U+++TI/-Tmp-/RtmpaKJps9/file14913e64153/lubridate-master'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library'  \
  --install-tests 

* installing *source* package ‘lubridate’ ...
** libs
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"      -c RcppExports.cpp -o RcppExports.o
llvm-gcc-4.2 -arch x86_64 -std=gnu99 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"   -fPIC  -mtune=core2 -g -O2  -c datetime.c -o datetime.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [RcppExports.o] Error 127 (ignored)
...

**Comment by vspinu** [comment] 2018-05-07 18:31
I really have no idea then :(  The gcc command seems to be truncated. It's surely the local tooling issue. Have you ever seen such things with other packages which require compilation?

**Comment by sylwiaoz** [comment] 2018-05-07 18:54
Nope... it went ok with the other ones I had to compile.

**Comment by hadley** [comment] 2019-11-19 22:11
Given that it works fine on CRAN and all our testing infrastructure, it's likely to be something specific to your setup.

**Closed by hadley** 2019-11-19 22:11 UTC

**Comment by barracuda156** [comment] 2021-11-30 12:16
> The issue is still there (the same I guess?):
>   /bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
>   make: [RcppExports.o] Error 127 (ignored)
>   ...

@sylwiaoz Have you been able to find a solution to this error?
