### ISSUE TITLE
Period division does not work as expected

### ISSUE THREAD

**Issue by jsilve24** [tidyverse/lubridate#863] opened 2020-02-24 19:32 UTC
Division by certain periods gives error :
```
Error in validObject(.Object) : 
  invalid class “Period” object: periods must have integer values 
```

```r
library(lubridate)
hours(6)/2 # does not give error because 6/2 is an integer
hours(5)/2 # gives an error because 5/2 is not an integer
```

Using lubridate version 1.7.4

I think this is pretty obviously wrong. 

Thanks, 
Justin

**Comment by vspinu** [comment] 2020-02-26 21:55
This was intended by the original author (@garrettgman) and we have a range of tests (like this [one](https://github.com/tidyverse/lubridate/blob/aee6ac282793db6c6c0e27a564668f5a979bbd89/tests/testthat/test-ops-division.R#L141)). 

Making non-integer division to work with periods is tricky because for units higher than hours periods have variable length, so propagating the division to smaller units is not possible. 

One way to avoid such puzzles would be to enable numeric components of a period instead of the integer ones as it is now, but it's a bit late for this I would say.

**Comment by jsilve24** [comment] 2020-02-27 13:20
I definitely appreciate the subtleties of software development. Things that seem simple are often not, and there can be a degree of artistic integrity at play -- e.g., ensuring complete consistency of the interface and adherence to a central design principle. 

Still, from the perspective of a user, this is suboptimal. I would far prefer to see 
hours(5)/2 result in 2 h 30m. You could even imagine converting everything to seconds and just rounding to the nearest whole number of the division then simplifying through modulo arithmetic to days/hours/minutes etc... 

Just my two cents. Thanks for all the hard work.

**Comment by vspinu** [comment] 2020-03-07 16:29
This one cannot be fixed in the near future. Marking with `refactor` to be considered in case of the potential lubridate refactoring.

**Closed by vspinu** 2020-03-07 16:29 UTC

**Comment by mdancho84** [comment] 2021-11-14 18:16
This should be fixed now. I have included upgrades to:
- `tk_make_timeseries()`: Now detects if a date is on the end of the month and adjusts the series accordingly. 
- `tk_make_future_timeseries()` Now detects if all `idx` values are on end of the month, and adjusts the future series accordingly.
