### ISSUE TITLE
`update()` function gives strange results when changing to the beginning of a leap year

### ISSUE THREAD

**Issue by ShanikaLW** [tidyverse/lubridate#956] opened 2021-03-03 11:24 UTC
When the` update()` function is used to change the `year` and `yday` it gives strange results when the actual year is a leap year.

What is the reason for this behavior?

```r
x <- ymd("2009-09-02")
update(x, year = 2008, yday = 1)
[1] "2008-01-02" # should be "2008-01-01"

x <- ymd("2009-02-28")
update(x, year = 2008, yday = 1)
[1] "2008-01-01" # it works

x <- ymd("2009-03-01")
update(x, year = 2008, yday = 1) 
[1] "2008-01-02" # doesn't work

year(x) <- 2008
yday(x) <- 1
x
[1] "2008-01-01" # as expected.
```

**Comment by DavisVaughan** [comment] 2021-05-25 14:39
Works with clock's year-day type since, by design, you can't update multiple components at once

``` r
library(clock)
library(magrittr)

x <- year_month_day(2009, 9, 2) %>%
  as_year_day()

x
#> <year_day<day>[1]>
#> [1] "2009-245"
 
x <- x %>%
  set_year(2008) %>%
  set_day(1)

x
#> <year_day<day>[1]>
#> [1] "2008-001"

as.Date(x)
#> [1] "2008-01-01"
```

<sup>Created on 2021-05-25 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by vspinu** [comment] 2022-11-02 21:35
Fixed in devel

``` r
library(lubridate, warn.conflicts = F)
#> Loading required package: timechange

x <- ymd("2009-09-02")
update(x, years = 2008, ydays = 1)
#> [1] "2008-01-01"

x <- ymd("2009-03-01")
update(x, years = 2008, ydays = 1) 
#> [1] "2008-01-01"
```

<sup>Created on 2022-11-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Closed by vspinu** 2022-11-02 21:35 UTC
Labels: bug, clock
