### ISSUE TITLE
Month addition doesn't work for November?

### ISSUE THREAD

**Issue by swt2c** [tidyverse/lubridate#698] opened 2018-07-20 21:10 UTC
```
> d <- as.POSIXct("2017-11-01")
> month(d) <- month(d) + 1
> d
[1] "2017-11-01 EDT"
```

**Comment by swt2c** [comment] 2018-07-20 21:21
Seems to have something to do with daylight savings time switch which happened on 2017-11-05.  If I use GMT, it works.

**Comment by crossxwill** [comment] 2019-07-27 07:19
Looks like this is a time zone issue. Works fine for me.

```r
> d <- as.POSIXct("2017-11-01")
> month(d) <- month(d) + 1
> d
[1] "2017-12-01 PST"
```

My session info:

```r
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] lubridate_1.7.4 forcats_0.4.0   stringr_1.4.0   dplyr_0.8.3     purrr_0.3.2     readr_1.3.1    
 [7] tidyr_0.8.3     tibble_2.1.3    ggplot2_3.2.0   tidyverse_1.2.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1       cellranger_1.1.0 pillar_1.4.2     compiler_3.6.1   tools_3.6.1     
 [6] zeallot_0.1.0    jsonlite_1.6     gtable_0.3.0     nlme_3.1-140     lattice_0.20-38 
[11] pkgconfig_2.0.2  rlang_0.4.0      cli_1.1.0        rstudioapi_0.10  haven_2.1.1     
[16] withr_2.1.2      xml2_1.2.0       httr_1.4.0       generics_0.0.2   vctrs_0.2.0     
[21] hms_0.5.0        grid_3.6.1       tidyselect_0.2.5 glue_1.3.1       R6_2.4.0        
[26] readxl_1.3.1     modelr_0.1.4     magrittr_1.5     backports_1.1.4  scales_1.0.0    
[31] rvest_0.3.4      assertthat_0.2.1 colorspace_1.4-1 stringi_1.4.3    lazyeval_0.2.2  
[36] munsell_0.5.0    broom_0.5.2      crayon_1.3.4    
```

**Comment by cderv** [comment] 2019-07-27 08:59
@swt2c in which timezone are you working ? 
Which timezone is `d` before transformation ? 

If I assume you are working in `EDT`, it seems to work for me.
Also, I would refer to lubridate documentation when trying to do arithmetic with date. There are special operator that will help (`%m+%` and `%m-%`)
https://lubridate.tidyverse.org/articles/lubridate.html#arithmetic-with-date-times

``` r
library(lubridate)
#> 
#> Attachement du package : 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date
packageVersion("lubridate")
#> [1] '1.7.4'
Sys.setenv(TZ="America/New_York")
d <- as.POSIXct("2017-11-01")
d
#> [1] "2017-11-01 EDT"
month(d) <- month(d) + 1
d
#> [1] "2017-12-01 EST"
# arithmetic with date and lubridate
d <- as.POSIXct("2017-11-01")
d
#> [1] "2017-11-01 EDT"
d %m+% months(1)
#> [1] "2017-12-01 EST"
```

<sup>Created on 2019-07-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by swt2c** [comment] 2019-07-29 22:34
@cderv, yes, I'm using EDT.

```
$ R

R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(lubridate)

Attaching package: ‘lubridate’

The following object is masked from ‘package:base’:

    date

> packageVersion("lubridate")
[1] ‘1.7.4’
> d <- as.POSIXct("2017-11-01")
> d
[1] "2017-11-01 EDT"
> month(d) <- month(d) + 1
> d
[1] "2017-11-01 EDT"
```

**Comment by crossxwill** [comment] 2019-07-30 01:07
@swt2c - It may be helpful if you shared your `sessionInfo()` to see if there are conflicting packages.

**Comment by swt2c** [comment] 2019-07-30 02:09
```
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lubridate_1.7.4

loaded via a namespace (and not attached):
[1] compiler_3.4.4 magrittr_1.5   tools_3.4.4    Rcpp_0.12.18   stringi_1.2.4 
[6] stringr_1.3.1 
```

```
> d
[1] "2017-11-01 EDT"
> lubridate::month(d) <- lubridate::month(d) + 1
> d
[1] "2017-11-01 EDT"
> 
```

**Comment by crossxwill** [comment] 2019-07-30 02:22
Would changing the time zone to "America/New_York" help you?

```r
> library(lubridate)

Attaching package: ‘lubridate’

The following object is masked from ‘package:base’:

    date

> 
> init_date <- as.POSIXct("2017-11-01")
> init_date
[1] "2017-11-01 PDT"
> 
> new_date <- force_tz(init_date, "America/New_York")
> new_date
[1] "2017-11-01 EDT"
> 
> month(new_date) <- month(new_date) + 1
> new_date
[1] "2017-12-01 EST"
```

My session.

```r
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lubridate_1.7.4

loaded via a namespace (and not attached):
[1] compiler_3.6.1 magrittr_1.5   tools_3.6.1    Rcpp_1.0.1     stringi_1.4.3 
[6] stringr_1.4.0 
```

**Comment by crossxwill** [comment] 2019-07-30 03:09
@swt2c  - this will solve your problem. You have to coerce the date to `Date` and then add back the time zone. This is a work-around.

```r
> init_date <- as.POSIXct("2017-11-01")
> init_date
[1] "2017-11-01 PDT"
> 
> new_date <- force_tz(init_date, "America/New_York")
> new_date
[1] "2017-11-01 EDT"
> 
> #### Fails on RHEL 7 ------
> 
> month(new_date) <- month(new_date) + 1
> new_date
[1] "2017-11-01 EDT"
> 
> ##### Work around ------
> 
> new_date2 <- as.Date(new_date)
> month(new_date2) <- month(new_date2) + 1
> 
> new_date3 <- ymd(new_date2, tz="America/New_York")
> new_date3
[1] "2017-12-01 EST"
```

The problem is the `+` operator in the `month<-` method. For some reason, it cannot handle some dates with the class `POSIXct` in RHEL 7.

```r
> getMethod("month<-")
Method Definition (Class "derivedDefaultMethod"):

  function (x, value)
  {
    if (!is.numeric(value)) {
      value <- pmatch(tolower(value), c("january", "february",
                                        "march", "june", "july", "august", "september", "october",
                                        "november", "december"))
    }
    x <- x + months(value - month(x))
  }
```

**Comment by crossxwill** [comment] 2019-07-30 06:21
@cderv - It appears that `as.POSIXct` behaves differently between Windows 7 and RHEL 7.

## Windows 7
```r
Browse[4]> object
[1] "2017-12-01 EDT"
Browse[4]> as.POSIXct(object)
[1] "2017-12-01 EST"
Browse[4]> class(object)
[1] "POSIXlt" "POSIXt" 
```

## RHEL 7
```r
Browse[4]> object
[1] "2017-12-01 EDT"
Browse[4]> as.POSIXct(object)
[1] "2017-11-30 23:00:00 EST"
Browse[4]> class(object)
[1] "POSIXlt" "POSIXt" 
```

## Full debug script
```r
library(lubridate)

debug(lubridate:::add_period_to_date)
debug(lubridate:::update.POSIXt)
debug(lubridate:::update_date_time)
debug(lubridate:::add_months)

init_date <- as.POSIXct("2017-11-01")
init_date

new_date <- force_tz(init_date, "America/New_York")
new_date

month(new_date) <- month(new_date) + 1
```

**Comment by cderv** [comment] 2019-07-30 06:28
Good to know. 
Does this works on both ? 
```r
d <- as.POSIXct("2017-11-01")
d
#> [1] "2017-11-01 EDT"
d %m+% months(1)
#> [1] "2017-12-01 EST"
```

Also `as.POSIXct` has a `tz` argument that may differ between system. Maybe lubridate's parser are safer here (`ymd`, `ymd_hms`, `parse_date_time`, ...)

This feels definitely like a Timezone thing... 🤔

**Comment by crossxwill** [comment] 2019-07-30 06:36
Yes. `%m+%` solves the problem on both Windows and Linux.

```r
library(lubridate)

d <- as.POSIXct("2017-11-01", tz="America/New_York")
d
# [1] "2017-11-01 EDT"  Windows 7; R 3.6.1
# [1] "2017-11-01 EDT"  RHEL 7; R 3.3.3

d %m+% months(1)
# [1] "2017-12-01 EST"   Windows 7; R 3.6.1
# [1] "2017-12-01 EST"   RHEL 7; R 3.3.3
```

**Comment by crossxwill** [comment] 2019-07-30 06:49
R-Core was aware of the bug in `as.POSIXct` since April of 2016. They have not fixed it.

https://bugs.r-project.org/bugzilla/show_bug.cgi?id=16852

The behavior of `as.POSIXct` differs between operating systems.

**Comment by hadley** [comment] 2019-11-19 22:47
Given that this problem appears to be a bug in base R, and there's an existing workaround using `%m+`, I'm going to close this issue.

**Closed by hadley** 2019-11-19 22:47 UTC
