### ISSUE TITLE
Warning in with_tz(Sys.time(), tzone) : Unrecognized time zone '' after upgrade to 1.7.3

### ISSUE THREAD

**Issue by vnijs** [tidyverse/lubridate#651] opened 2018-03-10 04:31 UTC
After upgrading to lubridate 1.7.3 I consistently get the warning below in a shiny app although I don't actually use the with_tz function anywhere in my code. After starting the app and refreshing the browser every tab change produces the warning. I'm having a hard time even tracing down where the issue originates. Any suggestions on how to track this warning down?

`Warning in with_tz(Sys.time(), tzone) : Unrecognized time zone ''`

FYI The code for the shiny app is linked below

Github: https://github.com/radiant-rstats/radiant.data
Install: 
`install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/")`

Session Info:

```
devtools::session_info()

> devtools::session_info()
Session info ---------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.423)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2018-03-09                  

Packages -------------------------------------------------------------------------------------------------------------------------------
 package      * version    date       source                                 
 assertthat     0.2.0      2017-04-11 CRAN (R 3.4.0)                         
 backports      1.1.2      2017-12-13 CRAN (R 3.4.3)                         
 base         * 3.4.3      2017-12-07 local                                  
 base64enc      0.1-3      2015-07-28 CRAN (R 3.4.0)                         
 bindr          0.1.0.9000 2018-02-06 Github (krlmlr/bindr@4b20179)          
 bindrcpp     * 0.2        2017-06-17 CRAN (R 3.4.0)                         
 bit            1.1-12     2014-04-09 CRAN (R 3.4.0)                         
 bit64          0.9-7      2017-05-08 CRAN (R 3.4.0)                         
 blob           1.1.0      2017-06-17 CRAN (R 3.4.0)                         
 broom        * 0.4.3      2017-11-20 CRAN (R 3.4.3)                         
 car            2.1-6      2017-11-19 CRAN (R 3.4.3)                         
 cellranger     1.1.0      2016-07-27 CRAN (R 3.4.0)                         
 codetools      0.2-15     2016-10-05 CRAN (R 3.4.3)                         
 colorspace     1.3-2      2016-12-14 CRAN (R 3.4.0)                         
 compiler       3.4.3      2017-12-07 local                                  
 crosstalk      1.0.0      2016-12-21 CRAN (R 3.4.0)                         
 curl           3.1        2017-12-12 CRAN (R 3.4.3)                         
 data.table     1.10.4-3   2017-10-27 CRAN (R 3.4.2)                         
 datasets     * 3.4.3      2017-12-07 local                                  
 DBI            0.7        2017-06-18 CRAN (R 3.4.0)                         
 devtools       1.13.4     2017-11-09 CRAN (R 3.4.2)                         
 digest         0.6.15     2018-01-28 CRAN (R 3.4.3)                         
 dplyr        * 0.7.4      2017-09-28 CRAN (R 3.4.2)                         
 DT             0.4.5      2018-03-08 Github (rstudio/DT@8ba54ab)            
 evaluate       0.10.1     2017-06-24 CRAN (R 3.4.1)                         
 feather        0.3.1      2016-11-09 CRAN (R 3.3.2)                         
 foreign        0.8-69     2017-06-22 CRAN (R 3.4.3)                         
 ggplot2      * 2.2.1      2016-12-30 CRAN (R 3.4.0)                         
 glue           1.2.0      2017-10-29 CRAN (R 3.4.2)                         
 graphics     * 3.4.3      2017-12-07 local                                  
 grDevices    * 3.4.3      2017-12-07 local                                  
 grid           3.4.3      2017-12-07 local                                  
 gridExtra      2.3        2017-09-09 CRAN (R 3.4.1)                         
 gtable         0.2.0      2016-02-26 CRAN (R 3.4.0)                         
 hms            0.4.0      2017-11-23 CRAN (R 3.4.3)                         
 htmltools      0.3.6      2017-04-28 CRAN (R 3.4.0)                         
 htmlwidgets    1.0        2018-01-20 CRAN (R 3.4.3)                         
 httpuv         1.3.5.9005 2018-02-28 Github (rstudio/httpuv@a9af282)        
 httr           1.3.1      2017-08-20 CRAN (R 3.4.1)                         
 import         1.1.0      2015-06-22 CRAN (R 3.4.0)                         
 jsonlite       1.5        2017-06-01 CRAN (R 3.4.0)                         
 knitr          1.20       2018-02-20 cran (@1.20)                           
 later          0.7.1      2018-02-28 Github (r-lib/later@885b00e)           
 lattice        0.20-35    2017-03-25 CRAN (R 3.4.3)                         
 lazyeval       0.2.1      2017-10-29 CRAN (R 3.4.2)                         
 lme4           1.1-15     2017-12-21 CRAN (R 3.4.3)                         
 lubridate    * 1.7.3      2018-02-27 CRAN (R 3.4.3)                         
 magrittr     * 1.5        2014-11-22 CRAN (R 3.4.0)                         
 markdown       0.8        2017-04-20 CRAN (R 3.4.0)                         
 MASS           7.3-48     2017-12-25 CRAN (R 3.4.3)                         
 Matrix         1.2-12     2017-11-20 CRAN (R 3.4.3)                         
 MatrixModels   0.4-1      2015-08-22 CRAN (R 3.4.0)                         
 memoise        1.1.0      2017-04-21 CRAN (R 3.4.0)                         
 methods      * 3.4.3      2017-12-07 local                                  
 mgcv           1.8-23     2018-01-15 CRAN (R 3.4.3)                         
 mime           0.5        2016-07-07 CRAN (R 3.4.0)                         
 minqa          1.2.4      2014-10-09 CRAN (R 3.4.0)                         
 mnormt         1.5-5      2016-10-15 CRAN (R 3.4.0)                         
 munsell        0.4.3      2016-02-13 CRAN (R 3.4.0)                         
 nlme           3.1-131.1  2018-02-16 CRAN (R 3.4.3)                         
 nloptr         1.0.4      2014-08-04 CRAN (R 3.4.0)                         
 nnet           7.3-12     2016-02-02 CRAN (R 3.4.3)                         
 parallel       3.4.3      2017-12-07 local                                  
 pbkrtest       0.4-7      2017-03-15 CRAN (R 3.4.0)                         
 pillar         1.1.0      2018-01-14 CRAN (R 3.4.3)                         
 pkgconfig      2.0.1      2017-03-21 CRAN (R 3.4.0)                         
 plotly       * 4.7.1      2017-07-29 CRAN (R 3.4.1)                         
 plyr           1.8.4      2016-06-08 CRAN (R 3.4.0)                         
 promises       0.1.0.9002 2018-02-28 Github (rstudio/promises@c4f0cd0)      
 pryr           0.1.4      2018-02-18 cran (@0.1.4)                          
 psych          1.7.8      2017-09-09 CRAN (R 3.4.3)                         
 purrr          0.2.4      2017-10-18 CRAN (R 3.4.2)                         
 quantreg       5.35       2018-02-02 CRAN (R 3.4.3)                         
 R6             2.2.2      2017-06-17 CRAN (R 3.4.0)                         
 radiant.data   0.9.0.16   2018-03-10 local                                  
 Rcpp           0.12.15    2018-01-20 CRAN (R 3.4.3)                         
 readr          1.1.1      2017-05-16 CRAN (R 3.4.0)                         
 readxl         1.0.0      2017-04-18 CRAN (R 3.4.0)                         
 reshape2       1.4.3      2017-12-11 CRAN (R 3.4.3)                         
 rlang          0.2.0.9000 2018-03-08 Github (tidyverse/rlang@2781908)       
 rmarkdown      1.9        2018-03-01 cran (@1.9)                            
 rprojroot      1.3-2      2018-01-03 cran (@1.3-2)                          
 RSQLite        2.0        2017-06-19 CRAN (R 3.4.1)                         
 rstudioapi     0.7.0-9001 2018-01-08 local                                  
 scales         0.5.0      2017-08-24 CRAN (R 3.4.1)                         
 shiny        * 1.0.5.9000 2017-09-12 local                                  
 shinyAce       0.2.2.3    2018-02-08 local                                  
 SparseM        1.77       2017-04-23 CRAN (R 3.4.0)                         
 splines        3.4.3      2017-12-07 local                                  
 stats        * 3.4.3      2017-12-07 local                                  
 stringi        1.1.6      2017-11-17 CRAN (R 3.4.2)                         
 stringr        1.3.0      2018-02-19 cran (@1.3.0)                          
 tibble       * 1.4.2      2018-01-22 cran (@1.4.2)                          
 tidyr        * 0.8.0      2018-01-29 cran (@0.8.0)                          
 tools          3.4.3      2017-12-07 local                                  
 utils        * 3.4.3      2017-12-07 local                                  
 viridisLite    0.3.0      2018-02-11 Github (sjmgarnier/viridisLite@91199d1)
 withr          2.1.1      2017-12-19 CRAN (R 3.4.3)                         
 xtable         1.8-2      2016-02-05 CRAN (R 3.4.0)                         
 yaml           2.1.17     2018-02-27 cran (@2.1.17)   
```

**Comment by vspinu** [comment] 2018-03-10 10:55
This should be fixed in master. Would you mind checking it up? 

I will re-release within a week or two.

(Really like the radiant idea btw. Looks really promising.)

**Comment by vnijs** [comment] 2018-03-10 15:05
Warning is gone with current master on GitHub. Excellent. Thank you @vspinu! Thanks also for the compliment about Radiant. Comments and suggestions welcome.

**Comment by shrektan** [comment] 2018-03-30 16:49
I also find that 1.7.3 reports something closes to`Unrecognized time zone ''` but it's an error says like `CCTZ can't convert time zone '' to xxx`... Tried very hard but can't reproduce it stable. I will see if the dev version could fix it or not...

**Comment by vnijs** [comment] 2018-04-02 23:10
Any updates on the CRAN time-line? It doesn't break anything but it ain't pretty :)

![lubridate](https://user-images.githubusercontent.com/2998956/38220663-3edd2e00-3690-11e8-896c-3dc722b47e36.png)

**Comment by vspinu** [comment] 2018-04-10 11:17
I was sick and couldn't work on this. Will push to CRAN within a day or two.

**Closed by vspinu** 2018-04-10 11:17 UTC

**Comment by vnijs** [comment] 2018-04-10 11:53
Excellent! Thanks @vspinu. Hope you feel fully recovered soon.
