### ISSUE TITLE
Issue during lubridate version 1.7.0 installation

### ISSUE THREAD

**Issue by amarchin** [tidyverse/lubridate#596] opened 2017-10-30 10:12 UTC
I am trying to install the version 1.7.0 of `lubridate` but I get this:

```
** testing if installed package can be loaded
Error: package or namespace load failed for ‘lubridate’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/lubridate/libs/lubridate.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/lubridate/libs/lubridate.so, 6): Symbol not found: __ZN4cctz14load_time_zoneERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEPNS_9time_zoneE
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/lubridate/libs/lubridate.so
  Expected in: flat namespace
 in /Library/Frameworks/R.framework/Versions/3.4/Resources/library/lubridate/libs/lubridate.so
Errore: loading failed
Esecuzione interrotta
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/lubridate’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/lubridate’

The downloaded source packages are in
	‘/private/var/folders/1h/2spknxfx68gf_5q2g1q4n78w0000gn/T/Rtmphq7b4S/downloaded_packages’
Warning message:
In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘lubridate’ had non-zero exit status
```

R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

**Comment by vspinu** [comment] 2017-10-30 10:31
Is this from CRAN? It installs well on linux, max and solaris. I presume it should be fine on mac as well. Can you purge/reinstall? Does `devtool::install_github` work?

**Comment by amarchin** [comment] 2017-10-30 10:35
I tried both solutions but unfortunately neither of them worked

**Comment by vspinu** [comment] 2017-10-30 14:44
That is almost surely a local issue. I am digging a Mac here to check, but in meanwhile [CRAN osx checks](https://cran.r-project.org/) showed no problems.

**Comment by vspinu** [comment] 2017-11-06 19:21
Looks like no-one else has the same issue and I don't see it on a local Mac machine. Closing this as non-reproducible. Please reopen if the issue persists. There is new version 1.7.1 now on CRAN, btw. Also reinstall your Rcpp. You might have an old version of it lying around.

**Closed by vspinu** 2017-11-06 19:21 UTC

**Comment by benvolioT** [comment] 2017-11-21 07:05
I'm having this issue also. Tried reinstalling Rcpp by running:

```
remove.packages('Rcpp')
install.packages('Rcpp')
```

That didn't help. Platform details:

```
> version
               _                           
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          4.2                         
year           2017                        
month          09                          
day            28                          
svn rev        73368                       
language       R                           
version.string R version 3.4.2 (2017-09-28)
nickname       Short Summer   
```



Any other suggestions?

**Comment by benvolioT** [comment] 2017-11-21 07:05
@amarchin - were you ever able to find a solution?

**Comment by ApurvShah007** [comment] 2020-09-22 01:10
No I have the same issue
