### ISSUE TITLE
floor_date() and ceiling_date(): allow rounding to an even grid starting from a user defined origin

### ISSUE THREAD

**Issue by GitHunter0** [tidyverse/lubridate#932] opened 2020-11-08 22:23 UTC
`lubridate::floor_date()` and `lubridate::ceiling_date()` round dates incorrectly in some cases. They seem to cluster by month, while they should instead consider the whole date range. 

Here is an example for 20 days period:
```
library(lubridate)
library(tibbletime)
library(timetk)
library(tidyverse)

timetk::m4_daily %>% 
  group_by(id) %>% 
  mutate("lubridate_floor" = lubridate::floor_date(date, unit="20 days")) %>% 
  mutate("lubridate_ceiling" = lubridate::ceiling_date(date, unit="20 days")) %>%
  mutate("date_groups" = tibbletime::partition_index(date, period="20 days")) %>%
  group_by(id, date_groups) %>% 
  mutate("tibbletime_floor" = dplyr::first(date), .after="lubridate_floor") %>% 
  mutate("tibbletime_ceiling" = dplyr::last(date)) %>% 
  ungroup() %>% 
  select(!c(date_groups, value))
```

Since `lubridate` appears to cluster the calculation by month, the intervals between the dates alternate between 20 days and 10 days, violating our specification of "20 days". The `tibbletime` columns contain the values that I believe are the correct/expected ones.

Thank you

**Comment by vspinu** [comment] 2020-11-10 06:11
This is not what is normally called minimal reproducible example. If I understand correctly you are not happy with the fact that lubridte rounding with days starts with the beginning of the month. For better or worse this is how it it

This is a duplicate of #925. A solution would be to add an extra argument `origin_unit` or something.

**Comment by GitHunter0** [comment] 2020-11-10 12:24
> This is not what is normally called minimal reproducible example. If I understand correctly you are not happy with the fact that lubridte rounding with days starts with the beginning of the month. For better or worse this is how it it
> 
> This is a duplicate of #925. A solution would be to add an extra argument `origin_unit` or something.

Hey @vspinu , thanks for the response. With all due respect the way `lubridate` treats those cases sometimes can be problematic. Other people have being complaining about that behavior too. For example, a "20 days" floor between "2014-07-21" and "2014-08-09" is expected to be "2014-07-21" all the way but `lubridate` returns "2020-08-01" for August observations, that's why I said it "clusters by month". Moreover, as it can be seen in my example above, our serie starts at "2014-07-03" but `floor()` rounds it to "2014-07-01", a day that is not even in the date range of our data frame.

I know that there must be a reason why lubridate makes things the way it does, however, could you please consider reopening this issue and implement an option like `origin_unit ` as you suggested?

`floor()` and `ceiling()` are incredibly useful functions but I know to a lot of users they would be even more if they allow the kind of behavior I mentioned.

**Comment by vspinu** [comment] 2020-11-10 15:53
Your understanding is correct. What you call "clustering by month" is what I call "origin of rounding is 1st of month". I see the use case when one would want to have the rounding origin be 1st of Januarry. See [this proposal](https://github.com/tidyverse/lubridate/issues/925#issuecomment-724481545) of how to fix this. 

> For example, a "20 days" floor between "2014-07-21" and "2014-08-09" is expected to be "2014-07-21" 

Why this particular day? Can you give more motivation behind your use case? I am not fully convinced that what you want to achieve make conceptual sense. What should be floor of `2014-08-10` then?

And BTW, this particular behavior is super easy to achieve with `floor_date(x, "month") + days(20)`. One need not have a special rounding for that.

**Comment by GitHunter0** [comment] 2020-11-11 17:51
Thanks very much for the feedback, @vspinu 

Sorry, I realize now that `floor_date()` and `ceiling_date()` are not 'wrong', I was just expecting a different kind of behavior. I use functions like `timetk::condense_period()` and `timetk::filter_period()` that employ those `lubridate` functions as backend and since they fail to produce the expected result in some cases we assumed was due to `lubridate`.

I believe the behavior I'm looking for is to `lubridate` round dates to the closest available in the serie for the interval provided without having 'the 1st of month as origin of rounding'. 

Here an example for 20 day intervals and this serie: 
```
x = as.Date(c(
 '2000-03-04', 
 '2000-03-22',
 '2000-03-25',
 '2000-04-12',
 '2000-04-15',
 '2000-04-29'
)) 
```

The function would first establish the regular 20 day intervals points starting from the first observation.

```
 interval_points = seq(from = first(x), by = '20 days', length.out = 1 + ceiling((last(x)-first(x))/20) ) ; interval_points 
 "2000-03-04" "2000-03-24" "2000-04-13" "2000-05-03"
```
The regular intervals would be: 
```
First:       [2000-03-04, 2000-03-24)
Second:  [2000-03-24, 2000-04-13)
Third:      [2000-04-13, 2000-05-03]
```

So `floor_date(x, option='consider only available dates')` for each point would be:
```
2000-03-04 -> 2000-03-04 (floor for the first interval)
2000-03-22 -> 2000-03-04 (floor for the first interval)
2000-03-25 -> 2000-03-25 (floor for the second interval)
2000-04-12 -> 2000-03-25 (floor for the second interval)
2000-04-15 -> 2000-04-15 (floor for the third interval)
2000-04-29 -> 2000-04-15 (floor for the third interval)
```

And `ceiling_date(x, option='consider only available dates')` for each point would be:

```
2000-03-04 -> 2000-03-22 (ceiling for the first interval)
2000-03-22 -> 2000-03-22 (ceiling for the first interval)
2000-03-25 -> 2000-04-12 (ceiling for the second interval)
2000-04-12 -> 2000-04-12 (ceiling for the second interval)
2000-04-15 -> 2000-04-29 (ceiling for the third interval)
2000-04-29 -> 2000-04-29 (ceiling for the third interval)
```

These are useful because later, among other things, we can filter a data frame to keep only the first or the last observation for each 20 day interval. 

So I think the difference would be to allow `floor_date()` and `ceiling_date()` to round to the closest available date and not have 'the 1st of month as origin of rounding'. 

Sorry if my explanation was a bit confusing, I hope you got the point.

**Comment by vspinu** [comment] 2020-11-11 19:18
So you basically want to have the ability to round to an evenly ditributed time grid. If we add an option to specify the rounding origin then it would solve your issue. You can specify the rounding origin to be your first observation or first of the year, or 1971-01-01 etc.

**Comment by vspinu** [comment] 2020-11-11 19:21
More generally, a user can supply the grid and then rounding to the closest. In other words alignment, or rolling in data.table parlance.

**Comment by GitHunter0** [comment] 2020-11-11 20:59
Yes @vspinu , I believe you got it perfectly, that option would be great!

**Closed** 2022-10-25 13:48 UTC
Labels: feature

**Comment by GitHunter0** [comment] 2022-10-25 16:56
Thank you @vspinu, could you provide some example?  I don't know how to replicate the result obtained in this issue.

**Comment by vspinu** [comment] 2022-10-27 19:16
Something along the following lines:

```R
> (x <- sort(ymd("2022-01-01") + minutes(sample(1000, 10))))
 [1] "2022-01-01 04:01:00 UTC" "2022-01-01 04:27:00 UTC" "2022-01-01 07:26:00 UTC"
 [4] "2022-01-01 08:27:00 UTC" "2022-01-01 08:49:00 UTC" "2022-01-01 09:28:00 UTC"
 [7] "2022-01-01 11:33:00 UTC" "2022-01-01 12:38:00 UTC" "2022-01-01 13:08:00 UTC"
[10] "2022-01-01 16:26:00 UTC"
> (grid <- ymd("2022-01-01") + hours(0:24))
 [1] "2022-01-01 00:00:00 UTC" "2022-01-01 01:00:00 UTC" "2022-01-01 02:00:00 UTC"
 [4] "2022-01-01 03:00:00 UTC" "2022-01-01 04:00:00 UTC" "2022-01-01 05:00:00 UTC"
 [7] "2022-01-01 06:00:00 UTC" "2022-01-01 07:00:00 UTC" "2022-01-01 08:00:00 UTC"
[10] "2022-01-01 09:00:00 UTC" "2022-01-01 10:00:00 UTC" "2022-01-01 11:00:00 UTC"
[13] "2022-01-01 12:00:00 UTC" "2022-01-01 13:00:00 UTC" "2022-01-01 14:00:00 UTC"
[16] "2022-01-01 15:00:00 UTC" "2022-01-01 16:00:00 UTC" "2022-01-01 17:00:00 UTC"
[19] "2022-01-01 18:00:00 UTC" "2022-01-01 19:00:00 UTC" "2022-01-01 20:00:00 UTC"
[22] "2022-01-01 21:00:00 UTC" "2022-01-01 22:00:00 UTC" "2022-01-01 23:00:00 UTC"
[25] "2022-01-02 00:00:00 UTC"
> floor_date(x, grid)
 [1] "2022-01-01 04:00:00 UTC" "2022-01-01 04:00:00 UTC" "2022-01-01 07:00:00 UTC"
 [4] "2022-01-01 08:00:00 UTC" "2022-01-01 08:00:00 UTC" "2022-01-01 09:00:00 UTC"
 [7] "2022-01-01 11:00:00 UTC" "2022-01-01 12:00:00 UTC" "2022-01-01 13:00:00 UTC"
[10] "2022-01-01 16:00:00 UTC"
```
