### ISSUE TITLE
Suggestion to support ISO week in the lubridate functions  

### ISSUE THREAD

**Issue by kbzsl** [tidyverse/lubridate#729] opened 2018-11-09 16:11 UTC
Is it possible to implement the  isoweek (%V) support in lubridate date parsers? 
(for example 2017-W2-3, in case of isoweek is 2017-jan-11)

**Comment by vspinu** [comment] 2018-11-11 11:14
Everything is possible but there should be a demand for this. I am afraid this is low priority and probably will happen only on parser rewrite/extraction from lubridate.

**Comment by hadley** [comment] 2019-11-19 23:11
Duplicate of #506 — you might want to thumbs up that issue just to register your interest.

**Closed by hadley** 2019-11-19 23:11 UTC
