### ISSUE TITLE
Relative weekday calculations: Closest wday, Next  wday, Previous wday

### ISSUE THREAD

**Issue by dbuijs** [tidyverse/lubridate#298] opened 2015-01-16 17:36 UTC
Some business and scheduling applications require relative weekday calculations: e.g. closest Monday, 3rd Tuesday of the month, last Wednesday of the month. It would be nice if there were functions that took a date and returned the date that was the closest, next or previous weekday (Sun, Mon, Tue, etc.). I've written my own functions for this, and will make them available when I next have time, but here's the pseudocode:

Closest weekday:
Accept valid date, valid target weekday as input 
(optional input flag to return only shift duration as a lubridate interval class)
Determine weekday of input date (with lubridate::wday)
Determine shift in days as -(input wday - target wday + 4) %% 7 - 3
Add calculated shift to input date (with lubdridate::days)
Return shifted date

Next weekday:
Accept valid date, valid target weekday as input
(optional input flag to return only shift duration as a lubridate interval class) 
Determine weekday of input date (with lubridate::wday)
Determine shift in days as -(input wday - target wday) %% 7
Add calculated shift to input date (with lubdridate::days)
Return shifted date

Previous weekday:
Accept valid date, valid target weekday as input
(optional input flag to return only shift duration as a lubridate interval class) 
Determine weekday of input date (with lubridate::wday)
Determine shift in days as (input wday - target wday) %% 7 *-1
Add calculated shift to input date (with lubdridate::days)
Return shifted date

Convenience functions could also be created, e.g.: closestSunday, nextMonday, prevThurs
These generic functions could then be combined trivially with existing lubridate functions to calculate more meaningful dates that have relative dates within a month such as pay days, holidays, etc. 

I'd love some feedback on whether there is interest in incorporating functions like this into the lubridate package and if so, guidance on naming and formatting that would make the code more consistent with the other functions in the package.  Also no objection at all to someone else implementing the pseudocode above or equivalent in future versions of lubridate. I'll try to submit my own code when I have time, but I'm not sure when that will be.

**Comment by dbuijs** [comment] 2015-01-17 03:09
It does occur to me, after thinking about the rest of the package that these functions could also be implemented as variants or floor, ceiling and round.

**Comment by vspinu** [comment] 2015-01-17 03:32
I thought you want to preserve smaller units (HMS). `floor_date` and friends don't preserve smaller units.

**Comment by dbuijs** [comment] 2015-01-18 22:03
The immediate applications I'm thinking of wouldn't need units smaller than the date. The two examples that come to mind are determining the dates of holidays that are relative to the day of the week in a month, and calculations involving pay periods which may be a fixed weekday relative to the month.

**Comment by imanuelcostigan** [comment] 2015-02-05 09:36
this is a either a duplicate of #21 or a close cousin

**Comment by jdthorpe** [comment] 2017-04-20 19:19
How about adding an infix operator for offsetting weekdays like [this one](http://stackoverflow.com/a/43460608/1519199)

**Comment by vspinu** [comment] 2017-05-01 17:25
The problem with infix is that it cannot accept extra arguments. For instance, do you want to include other holidays or not? The infix also doesn't address the OPs issue, which is more in line with floor and ceiling. 

The issue is more general and was discussed at length in #21, #341 and @imanuelcostigan created a [new package](https://github.com/imanuelcostigan/fmdates) to address some of the issues with "jumpy" calendars.

**Comment by hadley** [comment] 2019-11-19 21:45
See also https://github.com/DavisVaughan/almanac — I think it's now clear that this is out of the scope of lubridate.

**Closed by hadley** 2019-11-19 21:45 UTC
Labels: feature
